### ISSUE TITLE
Sending feedback to Twister

### ISSUE THREAD

**Issue by aurnik** [dplduffy/DJTT_MFT_FLStudio#1]
Hey, I wrote you on the IL forums but figured I'd try here as well. Did you ever get data getting sent from FL back to the Twister? I'm using your code but right now I can only get data flowing one way (Twister controls FL Studio, but I don't necessarily need a script for that)

**Comment by dplduffy** [comment]
sorry I wasn't following the thread on the IL boards.  It seems to be working here.  I just pushed an update that removes the old Macro Refresh in favor of the new OnRefresh for macros.  Does that help you?

**Comment by aurnik** [comment]
@dplduffy Appreciate you getting back to me and pushing the update, yeah it seems like I might've had everything set up correctly, but I'm still not getting any logs other than "On Init", "On Midi In", and "On Midi Msg". Maybe I'm missing a setting within FL that's preventing OnRefresh from getting called?

The extra functionality I set up that was working was using Knob 1 to scroll through mixer tracks, and Knob 2 controls the volume for the current mixer track and Knob 3 controls the panning for the current mixer track -- allowing you to have basic control of the entire mixer with 3 knobs. That all works fine (and I can submit a PR here if you want) but now I'm trying to get the correct levels to send back to the Twister to update the LED values for Knobs 2 & 3.
